### ISSUE TITLE
Can I get the source Code?

### ISSUE THREAD

**Issue by R1234A** [DoubangoTelecom/ultimateMICR-SDK#2]
Hi, 
Thanks for the robust implementation of OCR and served as SDK to use. May, I know the process of how have you trained the model like the inspiration or implementation of this work.

I am willing to build for myself so where to start and follow??

**Comment by DoubangoTelecom** [comment]
Hello, 
Thanks for your interest in oir product. Unfortunately this is a closed source project. We cannot disclose the source our technical details.
