### ISSUE TITLE
c# sample not returning values

### ISSUE THREAD

**Issue by TomasCastan** [DoubangoTelecom/ultimateMICR-SDK#29]
Hi, I'm interested in using this product but when testing the c# sample with the recommendeded configuration I always get the same result, the program just prints **Result: {"duration":73,"frame_id":0}**. (The duration value changes accordingly with each execution)
Am I missing something?
Thanks

**Comment by DoubangoTelecom** [comment]
Please share the full logs and the sample image you're using. Have you tried the image with https://www.doubango.org/webapps/micr/?

**Comment by DoubangoTelecom** [comment]
I have tried on multiple machines and I always get the correct result. "cmc7_1280x720.jpg" is a pretty simple image.
1/ try running https://github.com/DoubangoTelecom/ultimateMICR-SDK/blob/master/binaries/windows/x86_64/recognizer_cmc7.bat and see if it's working. This bat file uses the c++ sample with code at https://github.com/DoubangoTelecom/ultimateMICR-SDK/blob/master/samples/c%2B%2B/recognizer/recognizer.cxx.
2/ If it's working, make sure you're using the right image
3/ Change 'CONFIG_DEBUG_WRITE_INPUT_IMAGE'  at https://github.com/DoubangoTelecom/ultimateMICR-SDK/blob/99bfb57ef4837d2d8ea224d885dccdf12f605037/samples/csharp/recognizer/Program.cs#L54 value from `false` to `true` then run the C# sample again. You'll have a "ultimateMICR-input.png" image generated in the folder as recognizer.exe. Share with us "ultimateMICR-input.png". More info at https://www.doubango.org/SDKs/micr/docs/Debugging_the_SDK.html

**Comment by DoubangoTelecom** [comment]
Another option to try is disabling GPGPU acceleration (https://github.com/DoubangoTelecom/ultimateMICR-SDK/blob/99bfb57ef4837d2d8ea224d885dccdf12f605037/samples/csharp/recognizer/Program.cs#L90) and sharing the logs. I see that you've an Intel GPU which is used.

**Comment by TomasCastan** [comment]
Disabling the GPGPU acceleration did it! Thank you so much for your time and assistance.
