### ISSUE TITLE
Can t read some number

### ISSUE THREAD

**Issue by Rahma763** [DoubangoTelecom/ultimateMICR-SDK#3]
First of all, thanks for this project. It s really good. Then i tried to use the sample project exemple for Android but i cant read  2,6 and 8 number. It is replaces  by * for cmc7 font.  Can you help me please.

**Comment by DoubangoTelecom** [comment]
Thanks for your interest in our product. The binaries shared here are trial versions for non commercial use only: https://github.com/DoubangoTelecom/ultimateMICR-SDK/blob/master/LICENSE.
The binaries comes with some restrictions but allow testing the speed and accuracy. One of the restrictions is that these 3 chars are replaced with a *.
