### ISSUE TITLE
sample programs keeps stopping

### ISSUE THREAD

**Issue by Benais** [DoubangoTelecom/ultimateMICR-SDK#41]
![image](https://user-images.githubusercontent.com/1606329/124428305-34b32580-dd75-11eb-96d9-53945e7f6685.png)

all 3 sample programs keeps stopping at the moment i open them.
why is that happens?

thanks

**Comment by DoubangoTelecom** [comment]
Are you using an emulator? If yes, it's expected. The SDK requires ARM device.

**Comment by Benais** [comment]
Thanks it’s working now.
But I got 1 more problem
Cmc7 never recognize the numbers 8,2,6
I checked 5 different docs
