### ISSUE TITLE
CMC7 not recognizing few characters 

### ISSUE THREAD

**Issue by Benais** [DoubangoTelecom/ultimateMICR-SDK#42]
Cmc7 not recognizing the numbers 8,2,6
I checked 5 different real checks
And it always returning * for those numbers
There is a way to fix this?
![E5B2CF65-E2B3-4323-9695-5AAA85F27787](https://user-images.githubusercontent.com/1606329/124507094-b89cfa00-ddd5-11eb-80d9-5713caca5955.jpeg)

**Comment by DoubangoTelecom** [comment]
Without a valid license some characters are obfuscated and replaced with a '*'
