### ISSUE TITLE
problem running python sample program

### ISSUE THREAD

**Issue by Yaniv5001** [DoubangoTelecom/ultimateMICR-SDK#44]
I'm using ubuntu 21.04
Ive followed the install instructions in the `binaries/linux/x86_64` folder and added the tensorflow libs,
Ive ran python_setup.sh and got a normal output without any errors,
but when I try to run 
`ultimateMICR-SDK/samples/python/recognizer$ ./run_linux_x64.sh`
i get the following error
`./run_linux_x64.sh: line 3: 40790 Illegal instruction     (core dumped) PYTHONPATH=../../../binaries/linux/x86_64:../../../python LD_LIBRARY_PATH=../../../binaries/linux/x86_64:$LD_LIBRARY_PATH python3 recognizer.py --image ../../../assets/images/e13b_1280x720.jpg --format e13b --assets ../../../assets --backprop True --ielcd True
`
any clue on fixing this? Thank you in advanced!

**Comment by DoubangoTelecom** [comment]
Illegal instruction probably  indicate an old CPU without AVX2 (required by Tensorflow). Run `cat /proc/cpuinfo` and share the output. You can also try the native/c++ sample to see if you get illegal instruction issue.
