### ISSUE TITLE
Need information

### ISSUE THREAD

**Issue by Rahma763** [DoubangoTelecom/ultimateMICR-SDK#5]
I need information about how to get licence of iOS application sdk and how much It is cost. Can you help me please.

**Comment by Rahma763** [comment]
I tried to contact you by e mail but i didnt recieve responce yet and i am pressed by Time to begin my project.

**Comment by DoubangoTelecom** [comment]
If you're name is Rahma SOULI then, we sent you a response hours ago. Please check your Spam box.

**Comment by Rahma763** [comment]
Yes It is mine but i don t receive your e mail for licence informations. Please send me othor to soulirahma86@gmail.com. thanks you for help.

**Comment by DoubangoTelecom** [comment]
Sent again
