### ISSUE TITLE
QUESTIONS: TIFF image support and building for macos

### ISSUE THREAD

**Issue by smithbk** [DoubangoTelecom/ultimateMICR-SDK#59]
My use case is to perform OCR on a TIFF image from a X9.37 file.

Two questions please:

1. Does this SDK support TIFF directly?  The documentation at https://www.doubango.org/SDKs/micr/docs/Architecture_overview.html#supported-raw-formats doesn't mention TIFF

2. How do I build this SDK?  I want to evaluate it on macos.

Thanks

**Comment by DoubangoTelecom** [comment]
> My use case is to perform OCR on a TIFF image from a X9.37 file.
> 
> Two questions please:
> 
> 1. Does this SDK support TIFF directly?  The documentation at https://www.doubango.org/SDKs/micr/docs/Architecture_overview.html#supported-raw-formats doesn't mention TIFF
the link you have shared doesn't mention JPEG, PNG, BMP... but the sample programs support them. Same for TIFF, we support it.
> 2. How do I build this SDK?  I want to evaluate it on macos.
> 
macOS not supported
> Thanks
